### PR TITLE
API Key may be 36 character length

### PR DESCRIPTION
**Pull request by twocs**
Raised this issue in Zoom forums.
https://devforum.zoom.us/t/the-api-key-is-not-22-characters-so-why-is-the-code-checking-this-condition-it-is-36-characters/19220

### CODE REVIEW

**Comment by twocs** [comment]
Description
When I try to use the web SDK sample, I get an error in the console.
{method: "join", status: false, result: null, errorMessage: "Api key length error, must 22", errorCode: 4003}

This error is also reported by others
https://devforum.zoom.us/t/invalid-parameter-websdk-1-7-6/14070/3

There is a hard coded check in zoom-meeting-1.7.8.min.js that asserts the API_Key is length 22. Maybe some API Keys are that length (22 characters), but all the API Keys on our account have length 36.

So because of Zoom’s bug, we cannot use the SDK unless we edit the file zoom-meeting-1.7.8.min.js.


This is caused by code that checks API key length like this:

22!==Object(c.o)(i)?u="Api key length error, must 22"

This must be fixed. I know that some API keys are 22 length, others are 36. Any other possibilities? I edit the file zoom-meeting-1.7.8.min.js to correct this check

![22,36].includes(Object(c.o)(i))?u="Api key length error, must 22 or 36"

Now the web SDK code sample works.

Which version?
Web SDK 1.7.6, 1.7.7, 1.7.8

To Reproduce(If applicable)
Steps to reproduce the behavior:

Run the Web SDK with a 36 length API_key

**Comment by twocs** [comment]
Note: This is minified code. Someone should publish the original, but at least make the changes in the original pre-minification version!

**Comment by linjie997** [comment]
+1 for publishing the original code. Publishing the minified version is almost useless since it's extremely hard to contribute.

**Comment by banagale** [comment]
This appears to have been fixed, the logic in `zoomus-websdk.umd.min` is now: `22!==Object(c.n)(i)&&36!==Object(c.n)(i)?u="Api key length error, must 22/36"`

**Comment by mayk-zoom** [comment]
Closing PR as it is now outdated, thank you

**Pull request closed without merging**
